{{- if $.Values.auth2.monitoring }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-auth2-configmap-monitoring-scripts
  annotations:
    field.cattle.io/description: auth2 scripts
binaryData:
  auth2_startup: >- 
{{ include "auth2.auth2_startup" . | b64enc | indent 4 }}
  auth2_liveness: >- 
{{ include "auth2.auth2_liveness" . | b64enc | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-auth2-configmap-monitoring-htmls
  annotations:
    field.cattle.io/description: auth2 scripts
binaryData:
  auth2serverinfo.html: >- 
{{ $.Files.Get "static/auth2serverinfo.html" | b64enc | indent 4 }}
  auth2liveness.html: >- 
{{ $.Files.Get "static/auth2liveness.html" | b64enc | indent 4 }}
  auth2livenessfooter.html: >- 
{{ $.Files.Get "static/auth2livenessfooter.html" | b64enc | indent 4 }}

{{- end }}
