{{- $secrets := 0 }} 
{{- range $name,$data := $.Values.auth2.secrets }}
    {{- $secrets = add1 $secrets}}
{{- end }}
{{- range $name,$data := $.Values.auth2.secrets }}
{{- if gt $secrets 1 }}
---
{{- end }}
apiVersion: v1
data:
  {{- range $key,$value := $data }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
kind: Secret
metadata:
  name: {{ $.Release.Name }}-secret-{{ $name }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
