{{- if $.Values.auth2.monitor }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-auth2-configmap-monitoring-scripts
  annotations:
    field.cattle.io/description: auth2 scripts
binaryData:
  auth2_startup: >- 
{{ include "auth2.auth2_startup" . | b64enc | indent 4 }}
  auth2_liveness: >- 
{{ include "auth2.auth2_liveness" . | b64enc | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-auth2-configmap-monitoring-htmls
  annotations:
    field.cattle.io/description: auth2 scripts
binaryData:
  auth2serverinfo.html: >- 
{{ $.Files.Get "static/auth2serverinfo.html" | b64enc | indent 4 }}
  auth2monitoring.html: >- 
{{ $.Files.Get "static/auth2monitoring.html" | b64enc | indent 4 }}

---
{{- $config := $.Values.auth2.volume | default dict }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Name }}-auth2-monitoring-data
spec:
  accessModes:
    - {{ $config.accessMode | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ $config.storage | default "0.5Gi" | quote }}
  storageClassName: {{ $config.storageClassName | default "azurefile-csi-retain" }}
  volumeMode: {{ $config.volumeMode | default "Filesystem" }}
{{- end }}
