{{- $configmaps := 0 }} 
{{- range $name,$data := $.Values.auth2.configmaps }}
    {{- $configmaps = add1 $configmaps}}
{{- end }}
{{- range $name,$data := $.Values.auth2.configmaps }}
{{- if gt $configmaps 1 }}
---
{{- end }}
apiVersion: v1
data:
  {{- range $key,$value := $data }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
