apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: default
      port: {{ $.Values.auth2.port | default 8080 }}
      protocol: TCP
      targetPort: {{ $.Values.auth2.port | default 8080 }}
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-{{  $.Release.Namespace }}-{{ $.Release.Name }}
  sessionAffinity: None
  type: ClusterIP
