{{- $data := dict "auths" (dict ($.Values.auth2.secrets.imagepull.domain | default "ghcr.io")  (dict "username" ($.Values.auth2.secrets.imagepull.username ) "password" ($.Values.auth2.secrets.imagepull.password ) )) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-secret-imagepull
  namespace: {{ $.Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ toJson $data | b64enc }}
